"""empty message

Revision ID: 5557e897af33
Revises: 
Create Date: 2020-07-03 11:56:26.689014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5557e897af33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=6400), nullable=True),
    sa.Column('longitude', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_address'), 'places', ['address'], unique=False)
    op.create_index(op.f('ix_places_description'), 'places', ['description'], unique=False)
    op.create_index(op.f('ix_places_image_url'), 'places', ['image_url'], unique=False)
    op.create_index(op.f('ix_places_latitude'), 'places', ['latitude'], unique=False)
    op.create_index(op.f('ix_places_longitude'), 'places', ['longitude'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_longitude'), table_name='places')
    op.drop_index(op.f('ix_places_latitude'), table_name='places')
    op.drop_index(op.f('ix_places_image_url'), table_name='places')
    op.drop_index(op.f('ix_places_description'), table_name='places')
    op.drop_index(op.f('ix_places_address'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
